FROM node:16.8 as react-build
WORKDIR /app
COPY . .
RUN npm i --legacy-peer-deps
RUN npm run build
#ENV NODE_ENV 16.18.2

FROM nginx:alpine
COPY /nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=react-build /app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]

